spring:
  main:
    web-application-type: none
  application:
    name: Science Technology Search Engine

db:
  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: venomvenom--

model:
  deepvk:
    name: deepvk/USER-bge-m3
    modelPath: src/main/resources/model/checkpoint/USER-bge-m3.onnx
    tokenizerPath: src/main/resources/model/checkpoint/tokenizer.json
